"""Apply the structure guards to the real repository (story 1-1a, AC3/AC4).

The companion file ``test_checkers_selfcheck.py`` proves the checkers detect
violations. This file proves the real tree contains none - and, crucially,
records how many files each rule actually scanned.

That second part matters at 1-1a: ``pipelines/`` is still empty, so the pipeline
shape rule inspects zero files and passes without asserting anything. Rather
than let that hide, the coverage report below names every zero-scope rule
explicitly, and a test asserts the report says so.
"""

from __future__ import annotations

from pathlib import Path

from crm import config
from tests.structure import checkers

REPO_ROOT = config.PROJECT_ROOT
COVERAGE_REPORT = REPO_ROOT / "docs" / "implementation-artifacts" / "structure-guard-coverage.md"

# (rule id, human description, checker)
RULES = (
    ("AD-1 lane isolation", "crm/segment and crm/churn never meet crm/ltv", checkers.find_lane_violations),
    ("AD-9 layering", "crm/ never imports pipelines/", checkers.find_layering_violations),
    ("AD-9 campaign order", "matrix -> simulate -> sensitivity", checkers.find_campaign_order_violations),
    ("AD-8 pipeline shape", "stages <=40 lines, main() only", checkers.find_pipeline_shape_violations),
    ("AD-1 stateless common", "crm/common holds no fitted state", checkers.find_stateful_common_violations),
    ("AD-4 config single source", "crm/config.py is the only app config", checkers.find_extra_config_files),
)


def _run_all() -> list[tuple[str, str, list[str], int]]:
    return [(rule, desc, *check(REPO_ROOT)) for rule, desc, check in RULES]


def test_repository_has_no_structure_violations() -> None:
    results = _run_all()
    offenders = {rule: violations for rule, _desc, violations, _n in results if violations}

    assert not offenders, f"Structure violations found: {offenders}"


def test_coverage_report_is_written() -> None:
    """Emit the per-rule scan coverage so zero-scope rules are visible."""
    results = _run_all()

    lines = [
        "# Structure Guard Coverage",
        "",
        "Generated by `tests/structure/test_repo_structure.py`. Regenerate with `pytest`.",
        "",
        "`files scanned` is the honest scope of each rule against the CURRENT tree.",
        "A rule scanning 0 files is registered and working (see",
        "`test_checkers_selfcheck.py`) but is not yet exercised by real code - it",
        "starts biting the moment a matching file appears.",
        "",
        "| Rule | Enforces | Files scanned | Violations |",
        "|---|---|---|---|",
    ]
    for rule, desc, violations, scanned in results:
        scope = str(scanned) if scanned else "0 - NO FILES IN SCOPE YET"
        lines.append(f"| {rule} | {desc} | {scope} | {len(violations)} |")
    lines.append("")

    COVERAGE_REPORT.parent.mkdir(parents=True, exist_ok=True)
    COVERAGE_REPORT.write_text("\n".join(lines), encoding="utf-8")

    assert COVERAGE_REPORT.exists()


def test_zero_scope_rules_are_declared_not_silent() -> None:
    """A rule with nothing to scan must say so in the report, not pass quietly."""
    results = _run_all()
    zero_scope = [rule for rule, _desc, _v, scanned in results if scanned == 0]

    if not zero_scope:
        return  # every rule has real files in scope; nothing to declare

    assert COVERAGE_REPORT.exists(), "coverage report must exist before zero-scope rules can be declared"
    report = COVERAGE_REPORT.read_text(encoding="utf-8")
    for rule in zero_scope:
        row = next(line for line in report.splitlines() if line.startswith(f"| {rule} |"))
        assert "NO FILES IN SCOPE YET" in row, f"zero-scope rule '{rule}' is passing silently"


def test_structural_seed_matches_spine() -> None:
    """AC1: the directory skeleton matches the architecture spine."""
    expected = [
        "crm/config.py",
        "crm/common/__init__.py",
        "crm/segment/__init__.py",
        "crm/churn/__init__.py",
        "crm/campaign/__init__.py",
        "crm/ltv/__init__.py",
        "pipelines",
        "marts",
        "tests/structure",
        "requirements.txt",
        "pytest.ini",
    ]
    missing = [rel for rel in expected if not (REPO_ROOT / rel).exists()]

    assert not missing, f"Structural Seed incomplete: {missing}"


def test_gitignore_excludes_data_and_models_but_keeps_marts() -> None:
    """AC1: marts/ is the committed exception to the artifact exclusions."""
    ignore_text = (REPO_ROOT / ".gitignore").read_text(encoding="utf-8")
    patterns = {line.strip() for line in ignore_text.splitlines() if line.strip() and not line.startswith("#")}

    assert "data/" in patterns
    assert "models/" in patterns
    assert "marts/" not in patterns
