"""THE golden values of the committed mart - single source (story 4-4, H3).

Before this module, the golden numbers lived as literals in four places at
once: the mart tests, the schema doc, the dashboard spec's anchor table, and
the README's headline table. The dual-update contract between them was prose -
exactly the "unverified copy drifts" failure the 4-3/4-4 reviews kept finding.

Now the TESTS import from here, so a retrain that moves the mart turns every
stale copy red from one edit point. The three DOCUMENTS still carry the
numbers as text (a reader must not need Python to read a README), and the
document-contract tests compare those texts against THESE constants - the
docs are copies, this module is the source.

Measured on artifact 9e1a4d71800f (mart built 2026-07-23, deterministic).
"""

from __future__ import annotations

# Mart shape and totals
ROW_COUNT = 10_127
EXPECTED_SAVING_TOTAL = 1_454_088  # rounded display value; tests use abs=1.0

# Official 2x2 cuts (realised on this population)
RISK_CUT = 0.132753  # churn_score 0.75-quantile, 6dp as serialized
VALUE_CUT = 3_899.0  # customer_value median

# Official quadrant distribution
QUADRANT_COUNTS = {
    "low_cost_keep": 4_624,
    "accept_churn": 2_971,
    "watch": 2_089,
    "save_first": 443,
}

# Churn model metrics. SOURCE IS NOT COMMITTED: these come from
# models/churn_model.meta.json, a gitignored artifact regenerated by
# `pipelines/03_train_churn.py` (deterministic under AD-7 on a fixed
# environment). Recorded 2026-07-22; documents quoting them must say the
# source is a regenerable artifact, not a committed file.
PR_AUC = "0.9508"
PR_AUC_LIFT = "+40.8%"

# Display-formatted strings as they must appear in documents (comma format).
ROW_COUNT_TEXT = "10,127"
TOTAL_TEXT = "1,454,088"
RISK_CUT_TEXT = "0.132753"
VALUE_CUT_TEXT = "3,899"
QUADRANT_TEXTS = tuple(
    f"{name} {count:,}" for name, count in QUADRANT_COUNTS.items()
)
